# Generated by Django 3.2.4 on 2021-06-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('driverFullName', models.CharField(db_index=True, max_length=254)),
                ('registrationNumber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('IsActive', models.BooleanField(default=True)),
                ('status', models.CharField(default='Free', max_length=30)),
                ('lat', models.SmallIntegerField()),
                ('lon', models.SmallIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
