# Generated by Django 3.2.4 on 2021-06-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('riderFullName', models.CharField(db_index=True, max_length=255)),
                ('phone', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('billingAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('lat', models.SmallIntegerField()),
                ('lon', models.SmallIntegerField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
