# Generated by Django 3.2.4 on 2021-06-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabs', '0001_initial'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripId', models.UUIDField(db_index=True)),
                ('status', models.CharField(default='Yet To Start', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('pickupLocation', models.JSONField()),
                ('dropLocation', models.JSONField()),
                ('distance', models.SmallIntegerField(blank=True, null=True)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabs.cab')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
            ],
        ),
    ]
